[near]
[near.near_settings]
near_env="testnet"
near_node_url="https://near-testnet.infura.io/v3/dabe9e95376540b083ae09909ea7c576"
archival_near_node_url="https://archival-rpc.testnet.near.org"
wallet_url="https://wallet.testnet.near.org"
helper_url="https://helper.testnet.near.org"

[near.contracts]
registry_contract="registry.test_oct.testnet"
dao_contract_id="council-keeper.registry.test_oct.testnet"
oct_token_contract_id="oct.beta_oct_relay.testnet"

[[near.appchain_settings]]
appchain_name="barnacle0928"
appchain_id="barnacle0928"
subql_endpoint="https://api.subquery.network/sq/octopus-appchains/barnacle"
ws_rpc_endpoint="wss://gateway.testnet.octopus.network/barnacle0928/9mw012zuf27soh7nrrq3a4p0s2ti3cyn"

[[near.appchain_settings]]
appchain_name="barnacle-evm"
appchain_id="barnacle-evm"
subql_endpoint="https://api.subquery.network/sq/octopus-appchains/barnacle"
ws_rpc_endpoint="wss://gateway.testnet.octopus.network/barnacle-evm/wj1hhcverunusc35jifki19otd4od1n5"

[near.relayer_near_account]
id="test-relayer.testnet"
private_key="test"

[appchian]
appchain_id="barnacle0928"
start_block_height=1
update_start_min_interval=60